### ISSUE TITLE
USB Gadget

### ISSUE THREAD

**Issue by marcovilla118** [PocketPilot/PocketPilot#6]
Dear All,

I tried several time to load the operating system with no success. After installing the RT Kernel and rebooting the board then the shh via usb is not working, some times I can log in but then hang up. Tring ping sometimes is not working, it looks like the connection is flapping.

Anyone faced the same problem?

Thanks

**Comment by RobertCNelson** [comment]
Sadly, today, when you enable RT, the usb musb ip on the AM335x can be hit and miss..

Some kernel version works better, which are you using? `uname -r`

Regards,

**Comment by marcovilla118** [comment]
Hi,
root@beaglebone:/home/debian# uname -r
4.19.232-bone-rt-r75
root@beaglebone:/home/debian# 

it's working if I use the IOT debian image but if I use CONSOLE image it's not working. I don't know if for pocketpilot the IOT image is ok or not I will see.

There is another way to connect to the device? maybe via uart?!?!

Thanks for the support

**Comment by marcovilla118** [comment]
Finally I solved loading RT kernel 5.4. Now usb gadget is working as well.

**Comment by marcovilla118** [comment]
Finally I solved loading RT kernel 5.4. Now usb gadget is working as well.
