### ISSUE TITLE
pin config

### ISSUE THREAD

**Issue by marcovilla118** [PocketPilot/PocketPilot#7]
Dear all,
now I have another problem that I'm still trying to solve. I would like to enable ADC pin for battery voltage check but it's not possible because if I check in the system the analog PIN are not available. Check below? Any suggestion how to enable them?

Thanks

root@beaglebone:/home/debian# sudo /opt/scripts/tools/version.sh
git:/opt/scripts/:[9c0602cc5de15e35bcbff32e80511c72b03e7a16]
eeprom:[A335PBGL00A22220SPB01144]
model:[TI_AM335x_PocketBeagle]
dogtag:[BeagleBoard.org Debian Buster Console Image 2022-10-10]
bootloader:[microSD]:[/dev/mmcblk0]:[U-Boot SPL 2019.04-g923f8b8 (Jan 02 2022 - 19:05:15 +0000)]:[location: dd MBR]
bootloader:[microSD]:[/dev/mmcblk0]:[U-Boot 2019.04-g923f8b8]:[location: dd MBR]
UBOOT: Booted Device-Tree:[am335x-pocketbeagle.dts]
UBOOT: Loaded Overlay:[AM335X-PRU-RPROC-4-19-TI-00A0]
UBOOT: Loaded Overlay:[BB-ADC-00A0.kernel]
kernel:[5.4.209-bone-rt-r65]
/boot/uEnv.txt Settings:
uboot_overlay_options:[enable_uboot_overlays=1]
uboot_overlay_options:[uboot_overlay_pru=AM335X-PRU-RPROC-4-19-TI-00A0.dtbo]
uboot_overlay_options:[enable_uboot_cape_universal=1]
pkg check: to individually upgrade run: [sudo apt install --only-upgrade <pkg>]
pkg:[bb-cape-overlays]:[4.14.20210821.0-0~buster+20210821]
pkg:[bb-customizations]:[1.20220913.0-0~buster+20220913]
pkg:[bb-usb-gadgets]:[1.20220816.0-0~buster+20220816]
pkg:[bb-wl18xx-firmware]:[1.20211222.2-0~buster+20211222]
pkg:[kmod]:[26-1]
WARNING:pkg:[librobotcontrol]:[NOT_INSTALLED]
pkg:[firmware-ti-connectivity]:[20190717-2rcnee1~buster+20200305]
groups:[debian : debian adm kmem dialout cdrom floppy audio dip video plugdev users systemd-journal input bluetooth netdev gpio admin i2c tisdk weston-launch cloud9ide]
cmdline:[console=ttyS0,115200n8 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 lpj=1990656 rng_core.default_quality=100 quiet]
dmesg | grep remote
[    2.050681] remoteproc remoteproc0: wkup_m3 is available
[    2.251374] remoteproc remoteproc0: powering up wkup_m3
[    2.251394] remoteproc remoteproc0: Booting fw image am335x-pm-firmware.elf, size 217148
[    2.251663] remoteproc remoteproc0: remote processor wkup_m3 is now up
dmesg | grep pru
dmesg | grep pinctrl-single
[    1.790960] pinctrl-single 44e10800.pinmux: 142 pins, size 568
dmesg | grep gpio-of-helper
[    1.792668] gpio-of-helper ocp:cape-universal: Allocated GPIO id=0 name='P1_02'
[    1.792900] gpio-of-helper ocp:cape-universal: Allocated GPIO id=1 name='P1_04'
[    1.793259] gpio-of-helper ocp:cape-universal: Allocated GPIO id=2 name='P1_06'
[    1.793479] gpio-of-helper ocp:cape-universal: Allocated GPIO id=3 name='P1_08'
[    1.793662] gpio-of-helper ocp:cape-universal: Allocated GPIO id=4 name='P1_10'
[    1.793872] gpio-of-helper ocp:cape-universal: Allocated GPIO id=5 name='P1_12'
[    1.794079] gpio-of-helper ocp:cape-universal: Allocated GPIO id=6 name='P1_20'
[    1.794288] gpio-of-helper ocp:cape-universal: Allocated GPIO id=7 name='P1_26'
[    1.794535] gpio-of-helper ocp:cape-universal: Allocated GPIO id=8 name='P1_28'
[    1.795000] gpio-of-helper ocp:cape-universal: Allocated GPIO id=9 name='P1_29'
[    1.795395] gpio-of-helper ocp:cape-universal: Allocated GPIO id=10 name='P1_30'
[    1.795623] gpio-of-helper ocp:cape-universal: Allocated GPIO id=11 name='P1_31'
[    1.795835] gpio-of-helper ocp:cape-universal: Allocated GPIO id=12 name='P1_32'
[    1.796019] gpio-of-helper ocp:cape-universal: Allocated GPIO id=13 name='P1_33'
[    1.796234] gpio-of-helper ocp:cape-universal: Allocated GPIO id=14 name='P1_34'
[    1.796577] gpio-of-helper ocp:cape-universal: Allocated GPIO id=15 name='P1_35'
[    1.796782] gpio-of-helper ocp:cape-universal: Allocated GPIO id=16 name='P1_36'
[    1.797038] gpio-of-helper ocp:cape-universal: Allocated GPIO id=17 name='P2_01'
[    1.797289] gpio-of-helper ocp:cape-universal: Allocated GPIO id=18 name='P2_02'
[    1.797475] gpio-of-helper ocp:cape-universal: Allocated GPIO id=19 name='P2_03'
[    1.797691] gpio-of-helper ocp:cape-universal: Allocated GPIO id=20 name='P2_04'
[    1.797926] gpio-of-helper ocp:cape-universal: Allocated GPIO id=21 name='P2_05'
[    1.798109] gpio-of-helper ocp:cape-universal: Allocated GPIO id=22 name='P2_06'
[    1.798319] gpio-of-helper ocp:cape-universal: Allocated GPIO id=23 name='P2_07'
[    1.798549] gpio-of-helper ocp:cape-universal: Allocated GPIO id=24 name='P2_08'
[    1.798731] gpio-of-helper ocp:cape-universal: Allocated GPIO id=25 name='P2_09'
[    1.798991] gpio-of-helper ocp:cape-universal: Allocated GPIO id=26 name='P2_10'
[    1.799200] gpio-of-helper ocp:cape-universal: Allocated GPIO id=27 name='P2_11'
[    1.799385] gpio-of-helper ocp:cape-universal: Allocated GPIO id=28 name='P2_17'
[    1.799593] gpio-of-helper ocp:cape-universal: Allocated GPIO id=29 name='P2_18'
[    1.799802] gpio-of-helper ocp:cape-universal: Allocated GPIO id=30 name='P2_19'
[    1.800009] gpio-of-helper ocp:cape-universal: Allocated GPIO id=31 name='P2_20'
[    1.800218] gpio-of-helper ocp:cape-universal: Allocated GPIO id=32 name='P2_22'
[    1.800538] gpio-of-helper ocp:cape-universal: Allocated GPIO id=33 name='P2_24'
[    1.800795] gpio-of-helper ocp:cape-universal: Allocated GPIO id=34 name='P2_25'
[    1.801033] gpio-of-helper ocp:cape-universal: Allocated GPIO id=35 name='P2_27'
[    1.801255] gpio-of-helper ocp:cape-universal: Allocated GPIO id=36 name='P2_28'
[    1.801442] gpio-of-helper ocp:cape-universal: Allocated GPIO id=37 name='P2_29'
[    1.801654] gpio-of-helper ocp:cape-universal: Allocated GPIO id=38 name='P2_30'
[    1.801866] gpio-of-helper ocp:cape-universal: Allocated GPIO id=39 name='P2_31'
[    1.802072] gpio-of-helper ocp:cape-universal: Allocated GPIO id=40 name='P2_32'
[    1.802289] gpio-of-helper ocp:cape-universal: Allocated GPIO id=41 name='P2_33'
[    1.802541] gpio-of-helper ocp:cape-universal: Allocated GPIO id=42 name='P2_34'
[    1.802730] gpio-of-helper ocp:cape-universal: Allocated GPIO id=43 name='P2_35'
[    1.802741] gpio-of-helper ocp:cape-universal: ready
END

**Comment by juvinski** [comment]
Hi,
the analog pins are not available because you are loading the dtb to enable the analog pins - UBOOT: Loaded Overlay:[BB-ADC-00A0.kernel]
and when you do that, the config-pin cannot change the pin configuration once the pin was taked by the dtb

**Comment by RobertCNelson** [comment]
That just enables the analog ip block... Which should already be enabled by default..  what does iio_utils show

**Comment by marcovilla118** [comment]
what command or file I need to check about iio_utils?

**Comment by marcovilla118** [comment]
> Hi, the analog pins are not available because you are loading the dtb to enable the analog pins - UBOOT: Loaded Overlay:[BB-ADC-00A0.kernel] and when you do that, the config-pin cannot change the pin configuration once the pin was taked by the dtb

Ok but how I can disable it?

below the /boot/uEnv

root@beaglebone:/home/debian# more /boot/uEnv.txt 
#Docs: http://elinux.org/Beagleboard:U-boot_partitioning_layout_2.0

uname_r=5.4.209-bone-rt-r65
#uuid=
#dtb=

###U-Boot Overlays###
###Documentation: http://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_Overlays
###Master Enable
enable_uboot_overlays=1
###
###Overide capes with eeprom
#uboot_overlay_addr0=<file0>.dtbo
#uboot_overlay_addr1=<file1>.dtbo
#uboot_overlay_addr2=<file2>.dtbo
#uboot_overlay_addr3=<file3>.dtbo
###
###Additional custom capes
#uboot_overlay_addr4=<file4>.dtbo
#uboot_overlay_addr5=<file5>.dtbo
#uboot_overlay_addr6=<file6>.dtbo
#uboot_overlay_addr7=<file7>.dtbo
###
###Custom Cape
#dtb_overlay=<file8>.dtbo
###
###Disable auto loading of virtual capes (emmc/video/wireless/adc)
#disable_uboot_overlay_emmc=1
#disable_uboot_overlay_video=1
#disable_uboot_overlay_audio=1
#disable_uboot_overlay_wireless=1
#disable_uboot_overlay_adc=1
###
###PRUSS OPTIONS
###pru_rproc (4.14.x-ti kernel)
#uboot_overlay_pru=AM335X-PRU-RPROC-4-14-TI-00A0.dtbo
###pru_rproc (4.19.x-ti kernel)
#uboot_overlay_pru=AM335X-PRU-RPROC-4-19-TI-00A0.dtbo
###pru_uio (4.14.x-ti, 4.19.x-ti & mainline/bone kernel)
uboot_overlay_pru=AM335X-PRU-UIO-00A0.dtbo
###
###Cape Universal Enable
enable_uboot_cape_universal=1
###
###Debug: disable uboot autoload of Cape
#disable_uboot_overlay_addr0=1
#disable_uboot_overlay_addr1=1
#disable_uboot_overlay_addr2=1
#disable_uboot_overlay_addr3=1
###
###U-Boot fdt tweaks... (60000 = 384KB)
#uboot_fdt_buffer=0x60000
###U-Boot Overlays###

console=ttyS0,115200n8
cmdline=coherent_pool=1M net.ifnames=0 lpj=1990656 rng_core.default_quality=100 quiet

#In the event of edid real failures, uncomment this next line:
#cmdline=coherent_pool=1M net.ifnames=0 lpj=1990656 rng_core.default_quality=100 quiet video=HDMI-A-1:1024x768@6
0e

#Use an overlayfs on top of a read-only root filesystem:
#cmdline=coherent_pool=1M net.ifnames=0 lpj=1990656 rng_core.default_quality=100 quiet overlayroot=tmpfs

##enable Generic eMMC Flasher:
#cmdline=init=/opt/scripts/tools/eMMC/init-eMMC-flasher-v3.sh

**Comment by RobertCNelson** [comment]
```
sudo apt update
sudo apt install libiio-utils
```
Then check with:

```iio_info```

```
debian@BeagleBone:~$ iio_info 
Library version: 0.24 (git tag: v0.24)
Compiled with backends: local xml ip usb
IIO context created with local backend.
Backend version: 0.24 (git tag: v0.24)
Backend description string: Linux BeagleBone 5.10.140-ti-r52 #1bullseye SMP PREEMPT Sat Oct 8 19:56:05 UTC 2022 armv7l
IIO context has 2 attributes:
        local,kernel: 5.10.140-ti-r52
        uri: local:
IIO context has 1 devices:
        iio:device0: TI-am335x-adc.0.auto (buffer capable)
                8 channels found:
                        voltage0:  (input, index: 0, format: le:u12/16>>0)
                        1 channel-specific attributes found:
                                attr  0: raw value: 3896
                        voltage1:  (input, index: 1, format: le:u12/16>>0)
                        1 channel-specific attributes found:
                                attr  0: raw value: 3864
                        voltage2:  (input, index: 2, format: le:u12/16>>0)
                        1 channel-specific attributes found:
                                attr  0: raw value: 3960
                        voltage3:  (input, index: 3, format: le:u12/16>>0)
                        1 channel-specific attributes found:
                                attr  0: raw value: 1982
                        voltage4:  (input, index: 4, format: le:u12/16>>0)
                        1 channel-specific attributes found:
                                attr  0: raw value: 2106
                        voltage5:  (input, index: 5, format: le:u12/16>>0)
                        1 channel-specific attributes found:
                                attr  0: raw value: 3845
                        voltage6:  (input, index: 6, format: le:u12/16>>0)
                        1 channel-specific attributes found:
                                attr  0: raw value: 3812
                        voltage7:  (input, index: 7, format: le:u12/16>>0)
                        1 channel-specific attributes found:
                                attr  0: raw value: 3907
                1 buffer-specific attributes found:
                                attr  0: data_available value: 0
                No trigger on this device
```

```
debian@BeagleBone:~$ cat /sys/bus/iio/devices/iio\:device0/in*
3865
3871
3960
1975
1992
3685
3191
3907
```

Regards,

**Comment by marcovilla118** [comment]
> 

Thanks I did it. And it looks adc is working but I cannot use with configpin

root@beaglebone:/home/debian# 
root@beaglebone:/home/debian# iio_info
Library version: 0.19 (git tag: v0.19)
Compiled with backends: local xml ip usb serial
IIO context created with local backend.
Backend version: 0.19 (git tag: v0.19)
Backend description string: Linux beaglebone 5.4.209-bone-rt-r65 #1buster SMP PREEMPT Tue Sep 13 10:49:28 UTC 2022 armv7l
IIO context has 1 attributes:
	local,kernel: 5.4.209-bone-rt-r65
IIO context has 1 devices:
	iio:device0: TI-am335x-adc.0.auto (buffer capable)
		8 channels found:
			voltage0:  (input, index: 0, format: le:u12/16>>0)
			1 channel-specific attributes found:
				attr  0: raw value: 3840
			voltage1:  (input, index: 1, format: le:u12/16>>0)
			1 channel-specific attributes found:
				attr  0: raw value: 3797
			voltage2:  (input, index: 2, format: le:u12/16>>0)
			1 channel-specific attributes found:
				attr  0: raw value: 3938
			voltage3:  (input, index: 3, format: le:u12/16>>0)
			1 channel-specific attributes found:
				attr  0: raw value: 1937
			voltage4:  (input, index: 4, format: le:u12/16>>0)
			1 channel-specific attributes found:
				attr  0: raw value: 2086
			voltage5:  (input, index: 5, format: le:u12/16>>0)
			1 channel-specific attributes found:
				attr  0: raw value: 0
			voltage6:  (input, index: 6, format: le:u12/16>>0)
			1 channel-specific attributes found:
				attr  0: raw value: 0
			voltage7:  (input, index: 7, format: le:u12/16>>0)
			1 channel-specific attributes found:
				attr  0: raw value: 1700
		2 buffer-specific attributes found:
				attr  0: data_available value: 0
				attr  1: watermark value: 1
root@beaglebone:/home/debian# 
root@beaglebone:/home/debian# 
root@beaglebone:/home/debian# 
root@beaglebone:/home/debian# 
root@beaglebone:/home/debian# cat /sys/bus/iio/devices/iio\:device0/in*
3834
3798
3937
1922
2015
0
0
1708
root@beaglebone:/home/debian# 
root@beaglebone:/home/debian#

**Comment by RobertCNelson** [comment]
Why would you try to use config-pin on the ADC pins?

I had to double check the schematic..

https://git.beagleboard.org/beagleboard/pocketbeagle/-/blob/master/PocketBeagle_sch.pdf

They are wired directly to the header..

and there is no 'alliterative' configuration, they are ADC only... there is no pin mux...

![adc](https://user-images.githubusercontent.com/91469/200080709-4a4e95a5-1de4-4047-8b3a-b5a7d65cb156.png)


Regards,

**Comment by marcovilla118** [comment]
> 

I think now it's clear. ADC are not configurable so it has no sense what I was going to do :)

Thanks you so much for the explanation

**Comment by RobertCNelson** [comment]
I should add... there is one special adc..

![special](https://user-images.githubusercontent.com/91469/200081766-e45b3516-98ab-4d24-8ec3-0310b3657b1a.png)

You need to use "config-pin" to move GPIO87 as "floating", or hi-z... as we muxed an ADC with standard GPIO, for one special use-case..

Regards,

**Comment by marcovilla118** [comment]
Thanks I will
